openapi: '3.0.3'
info:
  title: U22 API
  version: '1.0'
servers:
  - url: http://{host-address}:3000
    description: APIのホスト環境
    variables:
      host-address:
        default: localhost
        enum:
          - localhost
paths:
  /login:
    get:
      summary: ログインページの表示
      responses:
        '200':
          description: OK
  /api/login:
    post:
      summary: ログイン処理
      description: メールアドレスとパスワードを送信してログインする
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                mail:
                  type: string
                  format: email
                  example: test@test.com
                password:
                  type: string
                  format: password
                  example: password
              required:
                - email
                - password
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
  /api/addModel:
    post:
      summary: モデルの追加
      description: モデルを追加する
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: string
                  format: user_id
                title:
                  type: string
                  format: title
                description:
                  type: string
                  format: description
                thumbnail:
                  type: string
                  format: thumbnail
                glb:
                  type: string
                  format: glb
              required:
                - title
                - description
                - thumbnail
                - glb
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    format: status
                    example: true
                  message:
                    type: string
                    format: message
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    format: status
                    example: false
                  message:
                    type: string
                    format: message
